package:
  name: identd
  version: 1.0.4
  epoch: 7
  description: Ident server returning a configurable static response
  target-architecture:
    - x86_64
  copyright:
    - paths:
        - "*"
      attestation: LICENSE
      license: MIT
  dependencies:
    runtime:
      - ca-certificates-bundle
      - tzdata

environment:
  contents:
    keyring:
      - https://alpinelinux.org/keys/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/v3.24/main
      - https://dl-cdn.alpinelinux.org/alpine/v3.24/community
      - https://git.mouse-lake.ts.net/api/packages/packages/alpine/v3.24/main
    packages:
      - busybox=1.37.0-r31
      - ca-certificates
      - git=2.54.0-r0
      - go=1.27.1-r19
      - go-licenses=2.0.1-r1
      - os-release=3.24.2-r0

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 1ce6f781efeed1c40eb38f10e52694959798f259
      repository: https://github.com/greboid/identd
      tag: v${{package.version}}
  - uses: go/build
    with:
      packages: ./
      output: identd
      static: "true"
  - uses: go/licenses
    with:
      checks: github.com/greboid/identd/LICENSE github.com/csmith/envflag/LICENCE
test:
  environment:
    contents:
      repositories:
        - https://dl-cdn.alpinelinux.org/alpine/v3.24/main
        - https://git.mouse-lake.ts.net/api/packages/packages/alpine/v3.24/main
      packages:
        - os-release=3.24.2-r0
        - busybox
  pipeline:
    - uses: test/paths
      with:
        executables: /usr/bin/identd
        files: /notices/github.com/greboid/identd/LICENSE /notices/github.com/csmith/envflag/LICENCE /usr/share/licenses/identd/LICENSE
update:
  enabled: true
  github:
    identifier: greboid/identd
    strip-prefix: v
    use-tag: true
