{{ set "repo" "csmith/dotege" -}}
{{- set "cmd" "cmd/dotege" -}}
{{- set "binary" "dotege" -}}
{{- set "directories" "templates" -}}
{{- set "volumes" "/config" "/certs" "/output" -}}

FROM {{image "golang"}} AS build
{{ partial "checkout-tag.gotpl" }}
{{ partial "static-go-build.gotpl" }}
{{ partial "copy-directories.gotpl" }}
{{ partial "create-directories.gotpl" }}
{{ partial "from-base-add-binary.gotpl" }}
