package:
  name: alpine
  description: Alpine Linux base image from minirootfs

versions:
  alpine: latest


stages:
  - name: verify
    environment:
      external-image: alpine
    pipeline:
      - name: Download and verify Alpine minirootfs
        uses: download-verify-extract
        with:
          url: "%{versions.alpine.url}"
          destination: fs.tar.gz
          checksum: "%{versions.alpine.checksum}"
          extract-dir: /rootfs
      - name: Add git config
        uses: copy-files
        with:
          files:
            - from: gitconfig
              to: /rootfs/etc/gitconfig
  - name: Final
    environment:
      external-image: scratch
      environment:
        LANG: en_US.UTF-8
      cmd:
        - /bin/sh
    pipeline:
      - name: Copy filesystem
        copy:
          from-stage: verify
          from: /rootfs/
          to: /
