package:
  name: alpine
  description: Alpine Linux base image from minirootfs

stages:
  - name: verify
    environment:
      external-image: alpine
      packages:
        - curl
      args:
        ARCHIVE_URL: "{{alpine_url}}"
        ARCHIVE_SUM: "{{alpine_checksum}}"
    pipeline:
      - name: Download and verify Alpine minirootfs
        uses: download-verify-extract
        with:
          url: ${ARCHIVE_URL}
          destination: fs.tar.gz
          checksum: ${ARCHIVE_SUM}
          extract-dir: /rootfs
      - name: Add git config
        uses: copy-files
        with:
          files:
            - from: gitconfig
              to: /rootfs/etc/gitconfig
  - name: Final
    environment:
      external-image: scratch
      environment:
        LANG: en_US.UTF-8
      cmd:
        - /bin/sh
    pipeline:
      - name: Copy filesystem
        copy:
          from-stage: verify
          from: /rootfs/
          to: /
