package:
  name: registryauth
  version: 1.0.20
  epoch: 11
  description: Docker registry token authentication server with an embedded registry
  target-architecture:
    - x86_64
  copyright:
    - paths:
        - "*"
      attestation: LICENSE
      license: MIT
  dependencies:
    runtime:
      - ca-certificates-bundle
      - tzdata

environment:
  contents:
    keyring:
      - https://alpinelinux.org/keys/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/v3.24/main
      - https://dl-cdn.alpinelinux.org/alpine/v3.24/community
      - https://git.mouse-lake.ts.net/api/packages/packages/alpine/v3.24/main
    packages:
      - busybox=1.37.0-r31
      - ca-certificates
      - git=2.54.0-r0
      - go=1.27.1-r22
      - go-licenses=2.0.1-r1
      - os-release=3.24.2-r0

vars:
  runtime-dirs: /data

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 341593a5575955de7898882d7cf22a30e1dce22f
      repository: https://github.com/greboid/registryauth
      tag: v${{package.version}}
  - uses: go/build
    with:
      packages: ./cmd/authedreg
      output: registryauth
      static: "true"
  - uses: dirs
    with:
      dirs: ${{vars.runtime-dirs}}
  - uses: go/licenses
    with:
      checks: github.com/greboid/registryauth/LICENSE github.com/csmith/envflag/LICENCE
test:
  environment:
    contents:
      repositories:
        - https://dl-cdn.alpinelinux.org/alpine/v3.24/main
        - https://git.mouse-lake.ts.net/api/packages/packages/alpine/v3.24/main
      packages:
        - os-release=3.24.2-r0
        - busybox
        - curl
  pipeline:
    - uses: test/paths
      with:
        executables: /usr/bin/registryauth
        files: /notices/github.com/greboid/registryauth/LICENSE /notices/github.com/csmith/envflag/LICENCE /usr/share/licenses/registryauth/LICENSE
        dirs: ${{vars.runtime-dirs}}
update:
  enabled: true
  github:
    identifier: greboid/registryauth
    strip-prefix: v
