package:
  name: pgvector
  version: 0.8.6
  epoch: 1
  description: Open-source vector similarity search for PostgreSQL
  target-architecture:
    - x86_64
  copyright:
    - paths:
        - "*"
      attestation: LICENSE
      license: PostgreSQL
  dependencies:
    runtime:
      - postgres-18=18.6-r1

environment:
  contents:
    keyring:
      - https://alpinelinux.org/keys/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/v3.24/main
      - https://dl-cdn.alpinelinux.org/alpine/v3.24/community
    packages:
      - busybox=1.37.0-r31
      - ca-certificates
      - git=2.54.0-r0
      - os-release=3.24.2-r0
      - build-base=0.5-r4
      - postgres-18=18.6-r1

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 8ee86c96f0fd72390f890aa8a336fda6d3ab4c6c
      repository: https://github.com/pgvector/pgvector
      tag: v${{package.version}}
  - name: Build and install pgvector
    runs: DESTDIR="${{targets.destdir}}" ./01-build-and-install-pgvector.sh
  - uses: license/install
test:
  environment:
    contents:
      repositories:
        - https://dl-cdn.alpinelinux.org/alpine/v3.24/main
      packages:
        - os-release=3.24.2-r0
        - busybox
  pipeline:
    - uses: test/paths
      with:
        files: /usr/lib/postgresql/vector.so /usr/share/postgresql/extension/vector.control /usr/share/licenses/pgvector/LICENSE
        dirs: /usr/include/postgresql/server/extension/vector
update:
  enabled: true
  github:
    identifier: pgvector/pgvector
    strip-prefix: v
    use-tag: true
