{{- $repo := "csmith/webhooked" -}}
FROM {{image "golang"}} AS build

{{ checkout_tag $repo }}
{{ go_build $repo "webhooked" "" (list) (list) (list) }}
{{ create_volumes "/home/nonroot/.config" "/data" }}
{{ from_base_add_binary "centauri" (list) (list) }}
