{{ set "repo" "csmith/webhooked" -}}
{{- set "binary" "webhooked" -}}

FROM {{image "golang"}} AS build
{{ partial "checkout-tag.gotpl" }}
{{ partial "static-go-build.gotpl" }}
{{ partial "from-base-add-binary.gotpl" }}
