package:
  name: webhooked
  description: webhooked service

stages:
  - template: go-app
    with:
      repo: https://github.com/csmith/webhooked
      binary: webhooked
      expose:
        - "8080"