package:
  name: irc-github
  description: irc-github service

stages:
  - template: go-app
    with:
      repo: https://github.com/greboid/irc-github
      binary: irc-github
      package: ./cmd/github
      expose:
        - "8080"