package:
  name: golang
  description: Go build environment on Alpine

stages:
  - name: build
    environment:
      base-image: alpine
      args:
        ARCHIVE_URL: "{{golang_url}}"
        ARCHIVE_SUM: "{{golang_checksum}}"
      environment:
        GOPATH: "/go"
        PATH: "$GOPATH/bin:/usr/local/go/bin:$PATH"
      packages:
        - gcc
        - musl-dev
        - git
    pipeline:
      - name: Download and verify Go
        uses: download-verify-extract
        with:
          url: ${ARCHIVE_URL}
          destination: go.tar.gz
          checksum: ${ARCHIVE_SUM}
          extract-dir: /usr/local

      - name: Bootstrap and install Go
        build-deps:
          - bash
          - go
          - git
        run: |
          set -eux;
          cd /usr/local/go/src
          GOROOT_BOOTSTRAP="$(go env GOROOT)" GOHOSTOS="linux" GOHOSTARCH="amd64" ./make.bash
          go install std
          rm -rf \
            /go.tar.gz \
            /root/.cache \
            /usr/local/go/pkg/*/cmd \
            /usr/local/go/pkg/bootstrap \
            /usr/local/go/pkg/obj \
            /usr/local/go/pkg/tool/*/api \
            /usr/local/go/pkg/tool/*/go_bootstrap \
            /usr/local/go/src/cmd/dist/dist;
          go install github.com/google/go-licenses@v1.6.0

      - name: Create GOPATH directories
        uses: create-directories
        with:
          directories:
            - path: $GOPATH/src
              permissions: "777"
            - path: $GOPATH/bin
              permissions: "777"
  - name: rootfs
    environment:
      base-image: alpine
      packages:
        - gcc
        - musl-dev
        - git
    pipeline:
      - name: Copy Go to rootfs
        copy:
          from-stage: build
          from: /usr/local/go
          to: /rootfs/usr/local/go
      - name: Copy GOPATH to rootfs
        copy:
          from-stage: build
          from: /go
          to: /rootfs/go
  - name: Final
    environment:
      base-image: alpine
      environment:
        GOPATH: "/go"
        PATH: "$GOPATH/bin:/usr/local/go/bin:$PATH"
      packages:
        - gcc
        - musl-dev
        - git
    pipeline:
      - name: Copy rootfs to root
        copy:
          from-stage: rootfs
          from: /rootfs/
          to: /
