package:
  name: golang
  description: Go build environment on Alpine

stages:
  - name: Final
    environment:
      base-image: alpine
      args:
        ARCHIVE_URL: "{{golang_url}}"
        ARCHIVE_SUM: "{{golang_checksum}}"
      environment:
        GOPATH: "/go"
        PATH: "$GOPATH/bin:/usr/local/go/bin:$PATH"
      packages:
        - gcc
        - musl-dev
        - git
    pipeline:
      - name: Download and verify Go
        uses: download-verify-extract
        with:
          url: $ARCHIVE_URL
          destination: go.tar.gz
          checksum: $ARCHIVE_SUM
          extract-dir: /usr/local

      - name: Bootstrap and install Go
        build-deps:
          - bash
          - go
          - git
        run: |
          set -eux;
          cd /usr/local/go/src
          GOROOT_BOOTSTRAP="$(go env GOROOT)" GOHOSTOS="linux" GOHOSTARCH="amd64" ./make.bash
          go install std
          rm -rf \
            /go.tar.gz \
            /root/.cache \
            /usr/local/go/pkg/*/cmd \
            /usr/local/go/pkg/bootstrap \
            /usr/local/go/pkg/obj \
            /usr/local/go/pkg/tool/*/api \
            /usr/local/go/pkg/tool/*/go_bootstrap \
            /usr/local/go/src/cmd/dist/dist;
          mkdir -p $GOPATH/src $GOPATH/bin;
          chmod -R 777 $GOPATH;
          go install github.com/google/go-licenses@v1.6.0
