package:
  name: irc-bot
  version: 5.0.8
  epoch: 2
  description: Extensible IRC bot with a gRPC plugin interface
  target-architecture:
    - x86_64
  copyright:
    - paths:
        - "*"
      attestation: LICENSE
      license: MIT
  dependencies:
    runtime:
      - ca-certificates-bundle
      - tzdata

environment:
  contents:
    keyring:
      - https://alpinelinux.org/keys/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/v3.24/main
      - https://dl-cdn.alpinelinux.org/alpine/v3.24/community
      - https://git.mouse-lake.ts.net/api/packages/packages/alpine/v3.24/main
    packages:
      - busybox=1.37.0-r31
      - ca-certificates
      - git=2.54.0-r0
      - go=1.26.8-r0
      - go-licenses=1.6.0-r2
      - os-release=3.24.2-r0

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 68bc23ad7c6ecd9d08f4f6595d2e57a43b90d4c2
      repository: https://github.com/greboid/irc-bot
      tag: v${{package.version}}
  - uses: go/build
    with:
      packages: ./cmd/bot
      output: irc-bot
      static: "true"
  - uses: go/licenses
    with:
      module: github.com/greboid/irc-bot/v5
test:
  environment:
    contents:
      repositories:
        - https://dl-cdn.alpinelinux.org/alpine/v3.24/main
        - https://git.mouse-lake.ts.net/api/packages/packages/alpine/v3.24/main
      packages:
        - os-release=3.24.2-r0
        - busybox
  pipeline:
    - uses: test/paths
      with:
        executables: /usr/bin/irc-bot
        files: /notices/github.com/greboid/irc-bot/v5/LICENSE /usr/share/licenses/irc-bot/LICENSE
update:
  enabled: true
  github:
    identifier: greboid/irc-bot
    strip-prefix: v
    use-tag: true
