FROM {{image "golang"}} AS build
{{template "clone" (map "repo" "tailscale/golink")}}
{{template "build-go" (map "subdir" "./cmd/golink")}}
{{template "go-licenses" (map "ignores" (arr "modernc.org/mathutil" "github.com/jmespath/go-jmespath"))}}
{{template "prepare" (map "name" "golink")}}
{{template "runtime" (map "name" "golink" "exposes" (arr "8080") "cmd" `["--sqlitedb", "/home/nonroot/golink.db"]`)}}
