package:
  name: golink
  description: Tailscale golink service

stages:
  - template: go-app
    with:
      repo: https://github.com/tailscale/golink
      binary: golink
      package: ./cmd/golink
      ignore: modernc.org/mathutil
      expose:
        - "8080"
      cmd:
        - --sqlitedb
        - /home/nonroot/golink.db
