FROM {{image "rust" }} as server

ARG TAG="{{github_tag "libreddit/libreddit"}}"

RUN set -eux; \
apk add git; \
git clone --depth=1 -b $TAG --single-branch https://github.com/libreddit/libreddit /src; \
cd /src

WORKDIR /src

RUN set -eux; \
apk add musl-dev gcc openssl-dev; \
cargo build --release

FROM {{image "base"}}
COPY --from=server /src/target/release/libreddit /
ENTRYPOINT ["/libreddit"]
