package:
  name: miniflux
  version: 2.3.3
  epoch: 14
  description: Minimalist and opinionated feed reader
  target-architecture:
    - x86_64
  copyright:
    - paths:
        - "*"
      attestation: miniflux.license
      license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle
      - tzdata

environment:
  contents:
    keyring:
      - https://alpinelinux.org/keys/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/v3.24/main
      - https://dl-cdn.alpinelinux.org/alpine/v3.24/community
      - https://git.mouse-lake.ts.net/api/packages/packages/alpine/v3.24/main
    packages:
      - busybox=1.37.0-r31
      - ca-certificates
      - git=2.54.0-r0
      - go=1.27.1-r12
      - os-release=3.24.2-r0

vars:
  commit: c4d54f87a81b30aa173fddf05d7ff83ae7da5796

pipeline:
  - uses: git-checkout
    with:
      expected-commit: c4d54f87a81b30aa173fddf05d7ff83ae7da5796
      repository: https://github.com/miniflux/v2
      tag: v${{package.version}}
  - uses: go/build
    with:
      packages: ./
      output: miniflux
      ldflags: -X miniflux.app/v2/internal/version.Version=${{package.version}} -X miniflux.app/v2/internal/version.Commit=${{vars.commit}}

test:
  environment:
    contents:
      repositories:
        - https://dl-cdn.alpinelinux.org/alpine/v3.24/main
        - https://git.mouse-lake.ts.net/api/packages/packages/alpine/v3.24/main
      packages:
        - os-release=3.24.2-r0
        - busybox
  pipeline:
    - uses: test/version
      with:
        flag: -version
update:
  enabled: true
  github:
    identifier: miniflux/v2
