package:
  name: go-licenses
  version: 2.0.1
  epoch: 11
  description: Collect license notices for Go packages and their dependencies
  target-architecture:
    - x86_64
  copyright:
    - paths:
        - "*"
      attestation: LICENSE
      license: Apache-2.0
  dependencies:
    runtime:
      - go
      - ca-certificates-bundle
      - busybox-binsh

environment:
  contents:
    keyring:
      - https://alpinelinux.org/keys/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/v3.24/main
      - https://dl-cdn.alpinelinux.org/alpine/v3.24/community
      - https://git.mouse-lake.ts.net/api/packages/packages/alpine/v3.24/main
    packages:
      - busybox=1.37.0-r31
      - ca-certificates
      - git=2.54.0-r0
      - go=1.27.1-r27
      - os-release=3.24.2-r0
  environment:
    GOTOOLCHAIN: local

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 3e084b0caf710f7bfead967567539214f598c0a2
      repository: https://github.com/google/go-licenses
      tag: v${{package.version}}
  - uses: go/build
    with:
      packages: ./
      output: go-licenses
  - name: Move the binary to libexec and install the wrapper
    runs: |
      mkdir -p "${{targets.destdir}}/usr/libexec"
      mv "${{targets.destdir}}/usr/bin/go-licenses" "${{targets.destdir}}/usr/libexec/go-licenses"
      install -Dm 0755 go-licenses-wrapper.sh "${{targets.destdir}}/usr/bin/go-licenses"
  - uses: license/install
update:
  enabled: true
  shared: true
  github:
    identifier: google/go-licenses
    strip-prefix: v
    tag-filter-prefix: v2
