FROM {{image "rust"}} AS build

ARG TAG={{github_tag "static-web-server/static-web-server"}}

RUN set -eux; \
    apk add --no-cache \
        {{range $key, $value := alpine_packages "git" "gcc" "musl-dev" "make" -}}
        {{$key}}={{$value}} \
        {{end}};

RUN set -eux; \
    git clone --depth=1 -b $TAG --single-branch https://github.com/static-web-server/static-web-server /src

WORKDIR /src

RUN set -eux; \
    cargo build --release
