package:
  name: sws
  description: Static web server

stages:
  - name: build
    environment:
      base-image: rust
      workdir: /src
    pipeline:
      - name: Clone and build static-web-server
        uses: clone-and-build-rust
        with:
          repo: https://github.com/static-web-server/static-web-server
          patches:
            - keepqueriesonrewrites.diff
  - name: rootfs
    environment:
      base-image: base
    pipeline:
      - name: Copy binary to rootfs
        copy:
          from-stage: build
          from: /main
          to: /rootfs/sws
  - name: Final
    environment:
      base-image: base
      entrypoint:
        - /sws
    pipeline:
      - name: Copy rootfs to root
        copy:
          from-stage: rootfs
          from: /rootfs/
          to: /
