package:
  name: sws
  description: Static web server

stages:
  - template: rust-app
    with:
      repo: https://github.com/static-web-server/static-web-server
      binary: sws
      workdir: /src
      patches:
        - keepqueriesonrewrites.diff