on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '**/Containerfile'
      - '**/Dockerfile'
      - 'README.md'
name: Update Workflow
jobs:
  update-workflow:
    runs-on: alpine
    outputs:
      changes: ${{ steps.commit.outputs['changes-detected'] }}
    steps:
      - name: Checkout source
        uses: actions/toolkit/git-checkout@master
        with:
          token: ${{ secrets.CONTEMPT_TOKEN }}
      - name: Setup Go
        uses: actions/toolkit/go-setup@master
        with:
          go-version: 'stable'
          cache: false
      - name: Install latest orchestrator
        run: |
          go install github.com/csmith/contempt/cmd/orchestrator@latest
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"
      - name: Run contempt orchestrator
        env:
          REGISTRY: ${{ secrets.REGISTRY }}
          TEMPLATE: .forgejo/workflows/update-containers.yml.gotpl
          OUTPUT: .forgejo/workflows/update-containers.yml
        run: orchestrator "$PWD"
      - name: Commit changes
        id: commit
        uses: actions/toolkit/git-commit@master
        with:
            message: "Update container workflow"
            name: ${{ secrets.GIT_USERNAME }}
            email: ${{ secrets.GIT_EMAIL }}
            files: '.forgejo/workflows/update-containers.yml'
            push: 'false'
      - name: Push changes
        uses: actions/toolkit/git-try-push@master
  update-containers:
    name: Update Containers
    needs:
      - update-workflow
    if: needs.update-workflow.outputs.changes != 'true'
    uses: ./.forgejo/workflows/update-containers.yml
    secrets: inherit
