package:
  name: legoergo
  description: legoergo service

stages:
  - uses: multi-go-app
    with:
      binaries:
        - repo: https://github.com/ergochat/ergo
          binary: ergo
        - repo: https://github.com/csmith/certwrapper
          binary: certwrapper
      extra-copies:
        - from: /src/ergochat/ergo/languages/
          to: /ircd-bin/languages/
      expose:
        - "8080"
      cmd:
        - /certwrapper
        - /ergo
        - run
        - --conf
        - /ircd/ircd.yaml