{{ set "repo" "greboid/irc-bot" -}}
{{- set "cmd" "cmd/bot" -}}
{{- set "binary" "irc-bot" -}}

FROM {{image "golang"}} AS build
{{ partial "checkout-tag.gotpl" }}
{{ partial "static-go-build.gotpl" }}
{{ partial "from-base-add-binary.gotpl" }}
