FROM {{image "golang"}} AS build
{{template "clone" (map "repo" "greboid/irc-bot")}}
ENV CGO_ENABLED=0
{{template "build-go" (map "subdir" "./cmd/bot")}}
{{template "go-licenses" (map)}}
{{template "prepare" (map "name" "irc-bot")}}
{{template "runtime" (map "name" "irc-bot" "exposes" (arr "8080"))}}
