# BOM: {"apk:binutils":"2.45.1-r0","apk:brotli-libs":"1.2.0-r0","apk:c-ares":"1.34.6-r0","apk:ca-certificates-bundle":"20251003-r0","apk:gcc":"15.2.0-r2","apk:git":"2.52.0-r0","apk:gmp":"6.3.0-r4","apk:go":"1.25.5-r0","apk:isl25":"0.25-r2","apk:jansson":"2.14.1-r0","apk:libatomic":"15.2.0-r2","apk:libcrypto3":"3.5.4-r0","apk:libcurl":"8.17.0-r1","apk:libexpat":"2.7.3-r0","apk:libgcc":"15.2.0-r2","apk:libgomp":"15.2.0-r2","apk:libidn2":"2.3.8-r0","apk:libpsl":"0.21.5-r3","apk:libssl3":"3.5.4-r0","apk:libstdc++":"15.2.0-r2","apk:libunistring":"1.4.1-r0","apk:mpc1":"1.3.1-r1","apk:mpfr4":"4.2.2-r0","apk:musl":"1.2.5-r21","apk:musl-dev":"1.2.5-r21","apk:nghttp2-libs":"1.68.0-r0","apk:nghttp3":"1.13.1-r0","apk:pcre2":"10.47-r0","apk:zlib":"1.3.1-r2","apk:zstd-libs":"1.5.7-r2","https://github.com/greboid/irc-bot":"v5.0.8","image:base":"d9acc80b66b995fd319058541cd28cebad8e24fc58adbfe33f292f2dd212e3f3","image:golang":"73b0914aad4dac26556f252899a9e190c1d380285bd00e9ab2b59477c37d5cc6"}

FROM reg.g5d.dev/golang@sha256:73b0914aad4dac26556f252899a9e190c1d380285bd00e9ab2b59477c37d5cc6 AS build

RUN apk add --no-cache --virtual .build-go-static-deps \
    binutils=2.45.1-r0 \
    brotli-libs=1.2.0-r0 \
    c-ares=1.34.6-r0 \
    ca-certificates-bundle=20251003-r0 \
    gcc=15.2.0-r2 \
    git=2.52.0-r0 \
    gmp=6.3.0-r4 \
    go=1.25.5-r0 \
    isl25=0.25-r2 \
    jansson=2.14.1-r0 \
    libatomic=15.2.0-r2 \
    libcrypto3=3.5.4-r0 \
    libcurl=8.17.0-r1 \
    libexpat=2.7.3-r0 \
    libgcc=15.2.0-r2 \
    libgomp=15.2.0-r2 \
    libidn2=2.3.8-r0 \
    libpsl=0.21.5-r3 \
    libssl3=3.5.4-r0 \
    libstdc++=15.2.0-r2 \
    libunistring=1.4.1-r0 \
    mpc1=1.3.1-r1 \
    mpfr4=4.2.2-r0 \
    musl=1.2.5-r21 \
    musl-dev=1.2.5-r21 \
    nghttp2-libs=1.68.0-r0 \
    nghttp3=1.13.1-r0 \
    pcre2=10.47-r0 \
    zlib=1.3.1-r2 \
    zstd-libs=1.5.7-r2 \
    ;

# Clone repository
RUN git clone --depth=1 --branch v5.0.8 "https://github.com/greboid/irc-bot" /src
# Download dependencies
WORKDIR /src
RUN go mod download
# Build binary
RUN CGO_ENABLED=0 go build -trimpath -tags 'netgo,osusergo' -ldflags='-s -w -extldflags "-static"' -o /main ./cmd/bot
# Generate license notices
RUN go run github.com/google/go-licenses@latest save ./cmd/bot --save_path=/notices/main
RUN apk del --no-network .build-go-static-deps


FROM reg.g5d.dev/base@sha256:d9acc80b66b995fd319058541cd28cebad8e24fc58adbfe33f292f2dd212e3f3 AS rootfs

COPY --from=build /main /rootfs/irc-bot

COPY --from=build /notices /rootfs/notices


FROM reg.g5d.dev/base@sha256:d9acc80b66b995fd319058541cd28cebad8e24fc58adbfe33f292f2dd212e3f3

COPY --from=rootfs /rootfs/ /

EXPOSE 8080

ENTRYPOINT ["/irc-bot"]


