package:
  name: irc-bot
  description: IRC bot service

stages:
  - template: go-app
    with:
      repo: https://github.com/greboid/irc-bot
      binary: irc-bot
      package: ./cmd/bot
      expose:
        - "8080"