package:
  name: irc-bot
  description: IRC bot service

stages:
  - name: build
    environment:
      base-image: golang
    pipeline:
      - name: Clone and build irc-bot
        uses: clone-and-build-go
        with:
          repo: https://github.com/greboid/irc-bot
          package: ./cmd/bot
  - name: rootfs
    environment:
      base-image: base
    pipeline:
      - name: Copy binary and notices to rootfs
        copy:
          from-stage: build
          from: /main
          to: /rootfs/irc-bot
      - copy:
          from-stage: build
          from: /notices
          to: /rootfs/notices
  - name: Final
    environment:
      base-image: base
      expose:
        - "8080"
      entrypoint:
        - /irc-bot
    pipeline:
      - name: Copy rootfs to root
        copy:
          from-stage: rootfs
          from: /rootfs/
          to: /
