{{ set "repo" "greboid/dsp" -}}
{{- set "cmd" "cmd" -}}
{{- set "binary" "dsp" -}}

FROM {{image "golang"}} AS build
{{ partial "checkout-tag.gotpl" }}
{{ partial "static-go-build.gotpl" }}
{{ partial "from-base-add-binary.gotpl" }}
