package:
  name: postgres-15
  description: PostgreSQL 15 database server

versions:
  postgres: latest:15

stages:
  - name: build
    environment:
      base-image: alpine
      args:
        ENTRYPOINT: "39c3dc7046f5f7909179a51e25f2a61158781d57"
      packages:
        - git
        - gcc
        - g++
        - make
        - readline-dev
        - zlib-dev
        - linux-headers
        - musl-locales
        - openssl-dev
        - scanelf
        - rsync
        - bash
        - perl
        - bison
        - flex
    pipeline:
      - name: Clone postgres docker entrypoint
        uses: clone
        with:
          repo: https://github.com/docker-library/postgres
          workdir: /src/docker-postgres
          commit: "39c3dc7046f5f7909179a51e25f2a61158781d57"

      - name: Build PostgreSQL
        uses: clone-and-build-autoconf
        with:
          repo: https://github.com/postgres/postgres
          workdir: /src/postgres
          tag: "%{versions.postgres}"
          configure-options:
            - --with-system-tzdata=/usr/share/zoneinfo
            - --with-includes=/usr/local/include
            - --with-libraries=/usr/local/lib
            - --with-ssl=openssl
          make-steps:
            - make -j$(nproc) world
            - make -j$(nproc) install
            - make -j$(nproc) -C contrib install

      - name: Prepare rootfs dependencies
        run: |
          set -eux;
          DEPS=$(scanelf --needed --nobanner --format '%n#p' --recursive -l /usr/local /usr/local/pgsql/bin /usr/bin/locale \
          | tr ',' '\n' \
          | sort -u \
          | awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }');
          mkdir /rootfs;
          for DEP in $DEPS; do \
            apk add "${DEP}"; \
            apk info -qL "${DEP}" | rsync -aq '--files-from=-' / /rootfs/; \
          done

      - name: Create essential directories
        uses: create-directories
        with:
          directories:
            - path: /rootfs/usr/bin
            - path: /rootfs/bin
            - path: /rootfs/usr/local/bin
            - path: /rootfs/var/lib/postgresql/data

      - name: Copy essential binaries
        run: |
          set -eux;
          cp /usr/bin/env /rootfs/usr/bin/env;
          cp /bin/sh /rootfs/bin/sh;
          cp /bin/ls /rootfs/bin/ls;
          cp /bin/cat /rootfs/bin/cat;
          cp /bin/bash /rootfs/bin/bash;
          cp /usr/bin/find /rootfs/usr/bin/find;
          cp /usr/bin/locale /rootfs/usr/bin/locale;
          cp /usr/bin/id /rootfs/usr/bin/id;
          cp /bin/mkdir /rootfs/bin/mkdir;
          cp /bin/chmod /rootfs/bin/chmod

      - name: Set up entrypoint script
        run: |
          set -eux;
          cp /src/docker-postgres/15/alpine/docker-entrypoint.sh /rootfs/usr/local/bin/entry.sh;
          chmod 777 /rootfs/usr/local/bin/entry.sh;
          chown 65532:65532 /rootfs/usr/local/bin/entry.sh

      - name: Copy PostgreSQL installation
        run: |
          set -eux;
          rsync -ap /usr/local/pgsql/ /rootfs/usr/local/pgsql/

      - name: Create volumes
        uses: create-directories
        with:
          directories:
            - path: /rootfs/var/lib/postgresql
              owner: "65532:65532"
              permissions: "777"
            - path: /rootfs/var/lib/postgresql/data
              owner: "65532:65532"
              permissions: "777"
            - path: /rootfs/var/run
              owner: "65532:65532"
              permissions: "777"
            - path: /rootfs/tmp
              owner: "65532:65532"
              permissions: "777"
            - path: /rootfs/docker-entrypoint-initdb.d
              owner: "65532:65532"
              permissions: "644"
  - name: Final
    environment:
      base-image: base
      environment:
        PATH: "/usr/local/pgsql/bin:$PATH"
        LANG: "en_US.utf8"
        PGDATA: "/var/lib/postgresql/data"
        PGHOST: "127.0.0.1"
        PGUSER: "postgres"
      expose:
        - "5432"
      stopsignal: SIGINT
      entrypoint:
        - /usr/local/bin/entry.sh
      cmd:
        - postgres
        - -c
        - listen_addresses=*
    pipeline:
      - name: Copy rootfs
        copy:
          from-stage: build
          from: /rootfs/
          to: /
