FROM {{image "golang"}} AS build
{{template "clone" (map "repo" "csmith/goplum")}}
ENV CGO_ENABLED=0
{{template "build-go" (map "subdir" "./cmd/goplum")}}
{{template "go-licenses" (map)}}
{{template "prepare" (map "name" "goplum")}}
{{template "runtime" (map "name" "goplum" "exposes" (arr "8080"))}}
