package:
  name: goplum
  description: goplum service

stages:
  - name: build
    environment:
      base-image: golang
      packages:
        - git
    pipeline:
      - name: Clone and Build
        uses: clone-and-build-go
        with:
          repo: https://github.com/csmith/goplum
          package: ./cmd/goplum
  - name: rootfs
    environment:
      base-image: base
    pipeline:
      - name: Copy binary and notices to rootfs
        copy:
          from-stage: build
          from: /main
          to: /rootfs/goplum
      - copy:
          from-stage: build
          from: /notices
          to: /rootfs/notices
  - name: Final
    environment:
      base-image: base
      expose:
        - "8080"
      entrypoint:
        - /goplum
    pipeline:
      - name: Copy rootfs to root
        copy:
          from-stage: rootfs
          from: /rootfs/
          to: /
