FROM {{image "golang"}} AS build
{{template "clone" (map "repo" "miniflux/v2")}}
{{template "build-go" (map "ldflags" ` -X miniflux.app/version.Version=$TAG -X miniflux.app/version.Commit=$TAG`)}}
{{template "go-licenses" (map)}}
{{template "prepare" (map "name" "miniflux")}}
{{template "runtime" (map "name" "miniflux")}}
