package:
  name: baseroot
  description: Minimal rootfs with user accounts and essential packages

stages:
  - name: build
    environment:
      base-image: alpine
      packages:
        - rsync
      rootfs-packages:
        - ca-certificates-bundle
        - musl
        - tzdata
    pipeline:
      - name: Create mount points and directories
        uses: create-directories
        with:
          directories:
            - path: /rootfs/tmp
              permissions: "01777"
            - path: /rootfs/proc
            - path: /rootfs/dev
            - path: /rootfs/sys
            - path: /rootfs/etc

      - name: Set up user accounts
        uses: setup-users-groups
        with:
          rootfs: /rootfs
          groups:
            - name: root
              gid: 0
            - name: nobody
              gid: 65534
            - name: nonroot
              gid: 65532
          users:
            - username: root
              uid: 0
              gid: 0
              home: /root
              shell: /sbin/nologin
            - username: nobody
              uid: 65534
              gid: 65534
              shell: /sbin/nologin
            - username: nonroot
              uid: 65532
              gid: 65532
              home: /home/nonroot
              shell: /sbin/nologin

      - name: Add git config
        uses: copy-files
        with:
          files:
            - from: gitconfig
              to: /rootfs/etc/gitconfig
  - name: final
    environment:
      external-image: scratch
      environment:
        SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt
    pipeline:
      - name: Copy rootfs
        copy:
          from-stage: build
          from: /rootfs/
          to: /
