{{ set "repo" "csmith/irc-distribution" -}}
{{- set "cmd" "cmd/distribution" -}}
{{- set "binary" "irc-distribution" -}}

FROM {{image "golang"}} AS build
{{ partial "checkout-tag.gotpl" }}
{{ partial "static-go-build.gotpl" }}
{{ partial "from-base-add-binary.gotpl" }}
