package:
  name: vaultwarden
  description: Unofficial Bitwarden server implementation

stages:
  - template: rust-app
    with:
      repo: "https://github.com/dani-garcia/vaultwarden"
      binary: vaultwarden
      features: "sqlite,enable_mimalloc"
      packages:
        - gcc
        - musl-dev
        - openssl-dev