FROM {{image "baseroot"}} AS build

RUN set -eux; \
    # Add packages into rootfs
    {{ range $key, $value := alpine_packages "libstdc++" "libc6-compat" -}}
      apk add --no-cache {{$key}}={{$value}}; \
      apk info -qL {{$key}} | rsync -aq --files-from=- / /rootfs/; \
    {{ end -}}

FROM scratch

COPY --from=build /rootfs/ /
