FROM {{image "alpine"}} AS build

RUN set -eux; \
    {{ range $key, $value := alpine_packages "rsync" -}}
      apk add --no-cache {{$key}}={{$value}}; \
    {{ end -}}
    # Add packages into rootfs
    {{ range $key, $value := alpine_packages "libstdc++" "libc6-compat" -}}
      apk add --no-cache {{$key}}={{$value}}; \
      apk info -qL {{$key}} | rsync -aq --files-from=- / /rootfs/; \
    {{ end -}}
    echo;

FROM {{image "baseroot"}}

COPY --from=build /rootfs/ /
