{{ set "repo" "greboid/httpredirect" -}}
{{- set "binary" "httpredirect" -}}

FROM {{image "golang"}} AS build
{{ partial "checkout-tag.gotpl" }}
{{ partial "static-go-build.gotpl" }}
{{ partial "from-base-add-binary.gotpl" }}
