FROM {{image "golang"}} AS build
{{template "clone" (map "repo" "greboid/httpredirect")}}
{{template "build-go" (map)}}
{{template "go-licenses" (map)}}
{{template "prepare" (map "name" "httpredirect")}}
{{template "runtime" (map "name" "httpredirect" "exposes" (arr "8080"))}}
