package:
  name: httpredirect
  description: httpredirect service

stages:
  - template: go-app
    with:
      repo: https://github.com/greboid/httpredirect
      binary: httpredirect
      expose:
        - "8080"