{{ set "repo" "cutlerydrawer/linx-server" -}}
{{- set "binary" "linx" -}}
{{- set "volumes" (list "/data/files" "/data/meta") -}}
{{- set "runargs" (list "-bind=0.0.0.0:8080" "-filespath=/data/files/" "-metapath=/data/meta/" "-sitename=linx" "-allowhotlink") -}}

FROM {{image "golang"}} AS build
{{ partial "checkout-tag.gotpl" }}
{{ partial "static-go-build.gotpl" }}
{{ partial "create-directories.gotpl" }}
{{ partial "from-base-add-binary.gotpl" }}
