package:
  name: linx-server
  description: Self-hosted file/code/media sharing website

stages:
  - name: build
    environment:
      base-image: golang
      packages:
        - git
    pipeline:
      - name: Clone and build
        uses: clone-and-build-go
        with:
          repo: https://github.com/csmith/linx-server
      - name: Make volumes
        run: |
          mkdir -p /data/files /data/meta;
          chown -R 65532:65532 /data
  - name: Final
    environment:
      base-image: base
      expose:
        - "8080"
      volume:
        - /data/files
        - /data/meta
      entrypoint:
        - /linx-server
        - -bind=0.0.0.0:8080
        - -filespath=/data/files/
        - -metapath=/data/meta/
      cmd:
        - -sitename=linx
        - -allowhotlink
    pipeline:
      - name: Copy binary and data
        copy:
          from-stage: build
          from: /main
          to: /linx-server
      - copy:
          from-stage: build
          from: /data
          to: /data
      - copy:
          from-stage: build
          from: /notices
          to: /notices
