package:
  name: irc-goplum
  version: 4.0.2
  epoch: 12
  description: irc-bot plugin reporting goplum alert results to IRC channels
  target-architecture:
    - x86_64
  copyright:
    - paths:
        - "*"
      attestation: LICENSE
      license: MIT
  dependencies:
    runtime:
      - ca-certificates-bundle
      - tzdata

environment:
  contents:
    keyring:
      - https://alpinelinux.org/keys/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/v3.24/main
      - https://dl-cdn.alpinelinux.org/alpine/v3.24/community
      - https://git.mouse-lake.ts.net/api/packages/packages/alpine/v3.24/main
    packages:
      - busybox=1.37.0-r31
      - ca-certificates
      - git=2.54.0-r0
      - go=1.27.1-r22
      - go-licenses=2.0.1-r1
      - os-release=3.24.2-r0

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 24beee137f3f9d7bbcd19c9c656d39398a13309e
      repository: https://github.com/greboid/irc-goplum
      tag: v${{package.version}}
  - uses: go/build
    with:
      packages: ./cmd/goplum
      output: irc-goplum
      static: "true"
  - uses: go/licenses
    with:
      module: github.com/greboid/irc-goplum/v4/cmd/goplum
test:
  environment:
    contents:
      repositories:
        - https://dl-cdn.alpinelinux.org/alpine/v3.24/main
        - https://git.mouse-lake.ts.net/api/packages/packages/alpine/v3.24/main
      packages:
        - os-release=3.24.2-r0
        - busybox
  pipeline:
    - uses: test/paths
      with:
        executables: /usr/bin/irc-goplum
        files: /notices/github.com/greboid/irc-goplum/v4/cmd/goplum/LICENSE /usr/share/licenses/irc-goplum/LICENSE
update:
  enabled: true
  github:
    identifier: greboid/irc-goplum
    strip-prefix: v
    use-tag: true
