{{ set "repo" "containrrr/watchtower" -}}
{{- set "binary" "watchtower" -}}
{{- set "buildvars" (list (printf "github.com/containrrr/watchtower/internal/meta.Version=$TAG%s" (tagsafe (get "binary")))) -}}

FROM {{image "golang"}} AS build
{{ partial "checkout-tag.gotpl" }}
COPY disable-slack.patch /
WORKDIR /src/{{ get "repo" }}
RUN git apply /disable-slack.patch
{{ partial "static-go-build.gotpl" }}
{{ partial "from-base-add-binary.gotpl" }}
