package:
  name: watchtower
  description: Automatically update running Docker containers

stages:
  - name: build
    environment:
      base-image: golang
      packages:
        - git
    pipeline:
      - name: Clone and build watchtower
        uses: clone-and-build-go
        with:
          repo: https://github.com/containrrr/watchtower
          patches:
            - disable-slack.patch
  - name: Final
    environment:
      base-image: base
      entrypoint:
        - /watchtower

    pipeline:
      - name: Copy binary and notices
        copy:
          from-stage: build
          from: /main
          to: /watchtower

      - copy:
          from-stage: build
          from: /notices
          to: /notices
