package:
  name: watchtower
  description: Automatically update running Docker containers

stages:
  - template: go-app
    with:
      repo: https://github.com/containrrr/watchtower
      binary: watchtower
      patches:
        - disable-slack.patch