package:
  name: immich
  description: High performance self-hosted photo and video management solution

versions:
  "https://github.com/immich-app/immich": latest

stages:
  - name: geodata
    environment:
      base-image: alpine
      workdir: /build/geodata
    pipeline:
      - name: Download geodata files
        build-deps:
          - curl
          - unzip
        run: |
          set -eux;
          curl -fsSL -o /build/geodata/cities500.zip https://download.geonames.org/export/dump/cities500.zip
          curl -fsSL -o /build/geodata/admin1CodesASCII.txt https://download.geonames.org/export/dump/admin1CodesASCII.txt
          curl -fsSL -o /build/geodata/admin2Codes.txt https://download.geonames.org/export/dump/admin2Codes.txt
          curl -fsSL -o /build/geodata/ne_10m_admin_0_countries.geojson https://raw.githubusercontent.com/nvkelso/natural-earth-vector/v5.1.2/geojson/ne_10m_admin_0_countries.geojson
          unzip /build/geodata/cities500.zip -d /build/geodata/
          date --iso-8601=seconds | tr -d "\n" > /build/geodata/geodata-date.txt

  - name: builder
    environment:
      base-image: node
      workdir: /app
    pipeline:
      - name: Clone and build immich-server
        build-deps:
          - git
          - python3
          - make
          - g++
          - libheif-dev
          - vips-dev
          - ffmpeg-dev
          - perl
        run: |
          set -eux;
          export CI=true
          git clone --branch %{versions.https://github.com/immich-app/immich} --single-branch https://github.com/immich-app/immich.git
          cd immich
          pnpm install --frozen-lockfile
          SHARP_IGNORE_GLOBAL_LIBVIPS=true pnpm --filter immich --frozen-lockfile build
          SHARP_FORCE_GLOBAL_LIBVIPS=true pnpm --filter immich --frozen-lockfile --prod --no-optional deploy /app/server-deploy
          # Verify dist directory exists in deployment
          ls -la /app/server-deploy/dist/ || (echo "ERROR: dist directory not found!" && exit 1)

  - name: plugins
    environment:
      base-image: node
      workdir: /app
    pipeline:
      - name: Copy immich repo and build plugins
        copy:
          from-stage: builder
          from: /app/immich
          to: /app/immich
      - name: Install mise and build plugins
        build-deps:
          - curl
          - bash
          - mise
        run: |
          set -eux
          # Work only in plugins directory to avoid parent mise.toml
          cd /app/immich/plugins
          mise trust
          # Install tools via mise
          mise install
          # Build plugins
          mise run build

  - name: rootfs
    environment:
      base-image: alpine
      packages:
        - busybox
        - bash
        - rsync
      rootfs-packages:
        - libheif
        - vips
        - vips-cpp
        - ffmpeg
        - libgomp
        - imagemagick
        - perl
        - exiftool
        - libstdc++
    pipeline:
      - name: Create data directories
        uses: create-directories
        with:
          directories:
            - path: /rootfs/usr/src/app/upload
              owner: "65532:65532"
            - path: /rootfs/usr/src/app/.reverse-geocoding-dump
              owner: "65532:65532"
      - name: Copy immich-server to rootfs
        copy:
          from-stage: builder
          from: /app/server-deploy
          to: /rootfs/usr/src/app
          chown: "65532:65532"
      - name: Copy geodata to rootfs
        copy:
          from-stage: geodata
          from: /build/geodata
          to: /rootfs/build/geodata
      - name: Copy plugin dist to rootfs
        copy:
          from-stage: plugins
          from: /app/immich/plugins/dist
          to: /rootfs/build/corePlugin/dist
      - name: Copy plugin manifest to rootfs
        copy:
          from-stage: plugins
          from: /app/immich/plugins/manifest.json
          to: /rootfs/build/corePlugin/manifest.json

  - name: Final
    environment:
      base-image: node
      workdir: /usr/src/app
      entrypoint:
        - node
      cmd:
        - dist/main
      environment:
        NODE_ENV: production
    pipeline:
      - name: Copy rootfs to root
        copy:
          from-stage: rootfs
          from: /rootfs/
          to: /
