package:
  name: thelounge
  description: Modern, responsive, and self-hosted web IRC client

versions:
  "https://github.com/thelounge/thelounge.git": latest

stages:
  - name: yarnbase
    environment:
      base-image: node
    pipeline:
      - name: Enable corepack
        run: corepack enable

  - name: builder
    environment:
      base-image: node
      environment:
        THELOUNGE_HOME: /var/opt/thelounge
      workdir: /app
    pipeline:
      - name: Install thelounge
        build-deps:
          - git
          - python3
          - busybox
        run: |
          set -eux;
          git clone --branch %{versions.https://github.com/thelounge/thelounge.git} --single-branch https://github.com/thelounge/thelounge.git
          cd thelounge
          yarn install
          NODE_ENV=production yarn build

      - name: Create nonroot home directory
        uses: create-directories
        with:
          directories:
            - path: /home/nonroot
              owner: "65532:65532"

  - name: rootfs
    environment:
      base-image: base
    pipeline:
      - name: Copy thelounge to rootfs
        copy:
          from-stage: builder
          from: /app/thelounge
          to: /rootfs/app/thelounge
      - name: Copy wrapper script to rootfs
        uses: copy-files
        with:
          files:
            - from: thelounge
              to: /rootfs/usr/local/bin/thelounge
              chmod: "755"
      - name: Copy nonroot home to rootfs
        copy:
          from-stage: builder
          from: /home/nonroot
          to: /rootfs/home/nonroot
  - name: Final
    environment:
      base-image: node
      environment:
        THELOUNGE_HOME: /var/opt/thelounge
      entrypoint:
        - thelounge
      packages:
        - bash
    pipeline:
      - name: Copy rootfs to root
        copy:
          from-stage: rootfs
          from: /rootfs/
          to: /
