package:
  name: identd
  description: identd service

versions:
  "https://github.com/greboid/identd": latest

stages:
  - template: go-app
    with:
      repo: https://github.com/greboid/identd
      tag: "%{versions.https://github.com/greboid/identd}"
      binary: identd
      expose:
        - "8080"