{{ set "repo" "greboid/irc-webhook" -}}
{{- set "cmd" "cmd/webhook" -}}
{{- set "binary" "irc-webhook" -}}

FROM {{image "golang"}} AS build
{{ partial "checkout-tag.gotpl" }}
{{ partial "static-go-build.gotpl" }}
{{ partial "from-base-add-binary.gotpl" }}
