package:
  name: irc-webhook
  description: irc-webhook service

stages:
  - name: build
    environment:
      base-image: golang
    pipeline:
      - name: Clone and build irc-webhook
        uses: clone-and-build-go
        with:
          repo: https://github.com/greboid/irc-webhook
          package: ./cmd/webhook
  - name: rootfs
    environment:
      base-image: base
    pipeline:
      - name: Copy binary and notices to rootfs
        copy:
          from-stage: build
          from: /main
          to: /rootfs/irc-webhook
      - copy:
          from-stage: build
          from: /notices
          to: /rootfs/notices
  - name: Final
    environment:
      base-image: base
      expose:
        - "8080"
      entrypoint:
        - /irc-webhook
    pipeline:
      - name: Copy rootfs to root
        copy:
          from-stage: rootfs
          from: /rootfs/
          to: /
