{{ set "repo" "greboid/dockercleanup" -}}
{{- set "cmd" "" -}}
{{- set "binary" "dockercleanup" -}}

FROM {{image "golang"}} AS build
{{ partial "checkout-tag.gotpl" }}
{{ partial "static-go-build.gotpl" }}
{{ partial "from-base-add-binary.gotpl" }}
