FROM {{image "golang"}} AS build
{{template "clone" (map "url" "https://tangled.org/tangled.org/core" "tag" (unreleased_git_tag "https://tangled.org/tangled.org/core"))}}
{{template "build-go" (map "cgo" "true" "subdir" "./cmd/knot")}}
{{template "go-licenses" (map "ignores" (arr "github.com/ipfs/bbloom" "github.com/multiformats/go-base36" "gitlab.com/yawning/secp256k1-voi/internal/fiat/secp256k1montgomery"))}}
{{template "prepare" (map "name" "knot")}}
COPY --from={{image "git"}} / /rootfs/
{{template "runtime" (map "name" "knot" "runtime_image" "baseroot")}}
