package:
  name: rust
  description: Rust build environment on Alpine

versions:
  "https://github.com/rust-lang/rust": latest
  "https://github.com/rust-lang/rustup": latest

stages:
  - name: build
    environment:
      base-image: alpine
      environment:
        RUSTUP_HOME: "/usr/local/rustup"
        CARGO_HOME: "/usr/local/cargo"
        PATH: "/usr/local/cargo/bin:$PATH"
        RUST_VERSION: "${RUSTTAG}"

    pipeline:
      - name: Download and verify rustup
        uses: download-verify-extract
        with:
          url: https://static.rust-lang.org/rustup/archive/%{versions.https://github.com/rust-lang/rustup}/x86_64-unknown-linux-musl/rustup-init
          destination: rustup-init
          checksum-url: https://static.rust-lang.org/rustup/archive/%{versions.https://github.com/rust-lang/rustup}/x86_64-unknown-linux-musl/rustup-init.sha256

      - name: Install Rust
        build-deps:
          - busybox
        run: |
          set -eux;
          chmod +x rustup-init;
          ./rustup-init -y --no-modify-path --profile minimal --default-toolchain %{versions.https://github.com/rust-lang/rust} --default-host x86_64-unknown-linux-musl;
          rm rustup-init*;
          chmod -R a+w $RUSTUP_HOME $CARGO_HOME;
          ln -s $CARGO_HOME/bin/cargo /usr/local/bin/cargo
  - name: rootfs
    environment:
      base-image: alpine
    pipeline:
      - name: Copy Rust to rootfs
        copy:
          from-stage: build
          from: /usr/local/rustup
          to: /rootfs/usr/local/rustup
      - name: Copy Cargo to rootfs
        copy:
          from-stage: build
          from: /usr/local/cargo
          to: /rootfs/usr/local/cargo
      - name: Copy cargo symlink to rootfs
        copy:
          from-stage: build
          from: /usr/local/bin/cargo
          to: /rootfs/usr/local/bin/cargo
  - name: Final
    environment:
      base-image: alpine
      environment:
        RUSTUP_HOME: "/usr/local/rustup"
        CARGO_HOME: "/usr/local/cargo"
        PATH: "/usr/local/cargo/bin:$PATH"
    pipeline:
      - name: Copy rootfs to root
        copy:
          from-stage: rootfs
          from: /rootfs/
          to: /
