package:
  name: node
  description: Node.js build environment on Alpine

stages:
  - name: build
    environment:
      base-image: alpine
      args:
        TAG: "{{github_tag \"nodejs/node\"}}"
      packages:
        - tar
        - xz
        - rsync
        - gnupg
        - bash
        - libstdc++
        - gcompat
        - curl
    pipeline:
      - name: Create directories
        uses: create-directories
        with:
          directories:
            - path: /src
            - path: /usr/local

      - name: Download and verify Node.js
        uses: download-verify-extract
        with:
          url: https://unofficial-builds.nodejs.org/download/release/${TAG}/node-${TAG}-linux-x64-musl.tar.xz
          destination: /node.tar.xz
          checksum-url: https://unofficial-builds.nodejs.org/download/release/${TAG}/SHASUMS256.txt
          checksum-pattern: ".*linux-x64-musl.tar.xz"
          extract-dir: /src

      - name: Install Node.js
        run: |
          rsync -ap /src/node*/ /usr/local/;
          rm -rf /usr/local/CHANGELOG.md;
          rm -rf /usr/local/LICENSE;
          rm -rf /usr/local/README.md

      - name: Install corepack
        run: npm install --global corepack
  - name: rootfs
    environment:
      base-image: alpine
      packages:
        - gcompat
        - libstdc++
        - git
    pipeline:
      - name: Copy Node.js to rootfs
        copy:
          from-stage: build
          from: /usr/local
          to: /rootfs/usr/local
  - name: Final
    environment:
      base-image: alpine
      packages:
        - gcompat
        - libstdc++
        - git
      cmd:
        - /usr/local/bin/node
    pipeline:
      - name: Copy rootfs to root
        copy:
          from-stage: rootfs
          from: /rootfs/
          to: /
