package:
  name: irc-distribution
  version: 1.1.0
  epoch: 12
  description: irc-bot plugin distributing webhook payloads to IRC channels
  target-architecture:
    - x86_64
  copyright:
    - paths:
        - "*"
      attestation: LICENCE
      license: MIT
  dependencies:
    runtime:
      - ca-certificates-bundle
      - tzdata

environment:
  contents:
    keyring:
      - https://alpinelinux.org/keys/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/v3.24/main
      - https://dl-cdn.alpinelinux.org/alpine/v3.24/community
      - https://git.mouse-lake.ts.net/api/packages/packages/alpine/v3.24/main
    packages:
      - busybox=1.37.0-r31
      - ca-certificates
      - git=2.54.0-r0
      - go=1.27.1-r22
      - go-licenses=2.0.1-r3
      - os-release=3.24.2-r0

pipeline:
  - uses: git-checkout
    with:
      expected-commit: e68323d3c24b5b6063832fe13972f63dfee24067
      repository: https://github.com/csmith/irc-distribution
      tag: v${{package.version}}
  - uses: go/build
    with:
      packages: ./cmd/distribution
      output: irc-distribution
      static: "true"
  - uses: go/licenses
    with:
      module: github.com/csmith/irc-distribution/cmd/distribution
      license: LICENCE
test:
  environment:
    contents:
      repositories:
        - https://dl-cdn.alpinelinux.org/alpine/v3.24/main
        - https://git.mouse-lake.ts.net/api/packages/packages/alpine/v3.24/main
      packages:
        - os-release=3.24.2-r0
        - busybox
  pipeline:
    - uses: test/paths
      with:
        executables: /usr/bin/irc-distribution
        files: /notices/github.com/csmith/irc-distribution/cmd/distribution/LICENCE /usr/share/licenses/irc-distribution/LICENCE
update:
  enabled: true
  github:
    identifier: csmith/irc-distribution
    strip-prefix: v
    use-tag: true
