package:
  name: soju
  description: IRC bouncer

stages:
  - uses: multi-go-app
    with:
      binaries:
        - repo: https://github.com/emersion/soju
          package: ./cmd/soju
          binary: soju
          go-tags: moderncsqlite
          ignore: "codeberg.org/emersion/soju"
          entrypoint: true
        - repo: https://github.com/emersion/soju
          package: ./cmd/sojuctl
          binary: sojuctl
          ignore: "codeberg.org/emersion/soju"
        - repo: https://github.com/emersion/soju
          package: ./cmd/sojudb
          binary: sojudb
          go-tags: moderncsqlite
          ignore: "codeberg.org/emersion/soju"
      volumes:
        - path: /data