package:
  name: irc-webhook
  version: 4.1.1
  epoch: 12
  description: irc-bot plugin offering webhook-to-IRC relaying with token management
  target-architecture:
    - x86_64
  copyright:
    - paths:
        - "*"
      attestation: LICENSE
      license: MIT
  dependencies:
    runtime:
      - ca-certificates-bundle
      - tzdata

environment:
  contents:
    keyring:
      - https://alpinelinux.org/keys/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/v3.24/main
      - https://dl-cdn.alpinelinux.org/alpine/v3.24/community
      - https://git.mouse-lake.ts.net/api/packages/packages/alpine/v3.24/main
    packages:
      - busybox=1.37.0-r31
      - ca-certificates
      - git=2.54.0-r0
      - go=1.27.1-r23
      - go-licenses=2.0.1-r1
      - os-release=3.24.2-r0

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 7b839a503adaf73b3511527b389848b982e2e477
      repository: https://github.com/greboid/irc-webhook
      tag: v${{package.version}}
  - uses: go/build
    with:
      packages: ./cmd/webhook
      output: irc-webhook
      static: "true"
  - uses: go/licenses
    with:
      module: github.com/greboid/irc-webhook/v4/cmd/webhook
test:
  environment:
    contents:
      repositories:
        - https://dl-cdn.alpinelinux.org/alpine/v3.24/main
        - https://git.mouse-lake.ts.net/api/packages/packages/alpine/v3.24/main
      packages:
        - os-release=3.24.2-r0
        - busybox
  pipeline:
    - uses: test/paths
      with:
        executables: /usr/bin/irc-webhook
        files: /notices/github.com/greboid/irc-webhook/v4/cmd/webhook/LICENSE /usr/share/licenses/irc-webhook/LICENSE
update:
  enabled: true
  github:
    identifier: greboid/irc-webhook
    strip-prefix: v
    use-tag: true
