FROM {{image "golang"}} AS build
{{template "clone" (map "repo" "greboid/irc-goplum")}}
ENV CGO_ENABLED=0
{{template "build-go" (map "subdir" "./cmd/goplum")}}
{{template "go-licenses" (map)}}
{{template "prepare" (map "name" "irc-goplum")}}
{{template "runtime" (map "name" "irc-goplum")}}
