{{ set "repo" "greboid/irc-notifier" -}}
{{- set "cmd" "cmd/notifier" -}}
{{- set "binary" "irc-notifier" -}}

FROM {{image "golang"}} AS build
{{ partial "checkout-tag.gotpl" }}
{{ partial "static-go-build.gotpl" }}
{{ partial "from-base-add-binary.gotpl" }}
