FROM {{image "golang"}} AS build
{{template "clone" (map "repo" "greboid/irc-notifier")}}
{{template "build-go" (map "subdir" "./cmd/notifier")}}
{{template "go-licenses" (map)}}
{{template "prepare" (map "name" "irc-notifier")}}
{{template "runtime" (map "name" "irc-notifier")}}
