package:
  name: irc-notifier
  description: irc-notifier service

stages:
  - template: go-app
    with:
      repo: https://github.com/greboid/irc-notifier
      binary: irc-notifier
      package: ./cmd/notifier
      expose:
        - "8080"