package:
  name: redis
  version: 8.10.2
  epoch: 1
  description: In-memory data store with disk persistence (statically linked)
  target-architecture:
    - x86_64
  copyright:
    - paths:
        - "*"
      attestation: LICENSE.txt
      license: RSAL-2.0 OR SSPL-1.0 OR AGPL-3.0-only
  dependencies:
    runtime:
      - ca-certificates-bundle
      - tzdata

environment:
  contents:
    keyring:
      - https://alpinelinux.org/keys/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/v3.24/main
      - https://dl-cdn.alpinelinux.org/alpine/v3.24/community
      - https://git.mouse-lake.ts.net/api/packages/packages/alpine/v3.24/main
    packages:
      - busybox=1.37.0-r31
      - ca-certificates
      - git=2.54.0-r0
      - os-release=3.24.2-r0
      - build-base=0.5-r4
      - linux-headers=7.0.0-r1
      - openssl-dev=3.5.9-r0
      - openssl-libs-static=3.5.9-r0
      - zlib-dev=1.3.2-r0
      - zlib-static=1.3.2-r0
      - pkgconf=2.5.1-r0
  environment:
    LDFLAGS: -static

vars:
  runtime-dirs: /home/nonroot/database

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 498ecd0d6d007db11ddb3aea9428552598a78622
      repository: https://github.com/redis/redis
      tag: ${{package.version}}
  - uses: autoconf/make
    with:
      targets: distclean
  - uses: autoconf/make
    with:
      targets: all
  - uses: dirs
    with:
      dirs: ${{vars.runtime-dirs}}
  - name: Install the config
    runs: |
      install -Dm755 src/redis-server "${{targets.destdir}}/usr/bin/redis"
      install -Dm644 redis-minimal.conf "${{targets.destdir}}/redis.conf"
  - uses: license/install
    with:
      license: LICENSE.txt
  - uses: strip
    with:
      opts: -s
test:
  environment:
    contents:
      repositories:
        - https://dl-cdn.alpinelinux.org/alpine/v3.24/main
        - https://git.mouse-lake.ts.net/api/packages/packages/alpine/v3.24/main
      packages:
        - os-release=3.24.2-r0
        - busybox
  pipeline:
    - uses: test/paths
      with:
        executables: /usr/bin/redis
        files: /redis.conf /usr/share/licenses/redis/LICENSE.txt
        dirs: ${{vars.runtime-dirs}}
update:
  enabled: true
  github:
    identifier: redis/redis
