FROM {{image "golang"}} AS build
{{template "clone" (map "repo" "csmith/centauri-docker-confd")}}
ENV CGO_ENABLED=0
{{template "build-go" (map)}}
{{template "go-licenses" (map)}}
{{template "prepare" (map "name" "centauri-docker-confd")}}
{{template "runtime" (map "name" "centauri-docker-confd")}}
