FROM {{image "golang"}} AS build
{{template "clone" (map "repo" "csmith/purser")}}
{{template "build-go" (map "go_experiments" (arr "jsonv2"))}}
{{template "go-licenses" (map "go_experiments" (arr "jsonv2") "ignores" (arr "github.com/xi2/xz" "modernc.org/mathutil"))}}
{{template "prepare" (map "name" "purser" "volumes" (arr "/data/cache" "/data/output"))}}
{{template "runtime" (map "name" "purser" "volumes" (arr "/data/cache" "/data/output"))}}
