FROM {{image "alpine"}}

# Install packages
RUN set -eux; \
    apk add --no-cache \
    {{- range $key, $value := alpine_packages "rsync" "texlive" "texlive-xetex" "texmf-dist-latexextra"}}
        {{$key}}={{$value}} \
    {{- end}}
    ;

WORKDIR /home/nonroot


