package:
  name: texlive
  description: TeX Live LaTeX environment

stages: 
  - name: Final
    environment:
      base-image: alpine
      packages:
        - rsync
        - texlive
        - texlive-xetex
        - texmf-dist-latexextra
      workdir: /home/nonroot
