{{- $repo := "dexidp/dex" -}}
{{- $binary := "dockercleanup" -}}
FROM {{image "golang"}} AS build
{{ install_build_deps "sqlite" "gcc" }}
{{ create_volumes "/db" }}
{{ checkout_tag $repo }}
{{ go_build $repo $binary "cmd/dex" (list) (list) (list "github.com/dexidp/dex/api/v2") }}
{{ copy_directories $repo "/web" }}
{{ from_base_add_binary $binary (list) (list "serve" "/config.yml") }}
