# BOM: {"apk:binutils":"2.45.1-r0","apk:brotli-libs":"1.2.0-r0","apk:busybox":"1.37.0-r30","apk:c-ares":"1.34.6-r0","apk:ca-certificates-bundle":"20251003-r0","apk:gcc":"15.2.0-r2","apk:git":"2.52.0-r0","apk:gmp":"6.3.0-r4","apk:go":"1.25.5-r0","apk:isl25":"0.25-r2","apk:jansson":"2.14.1-r0","apk:libatomic":"15.2.0-r2","apk:libcrypto3":"3.5.4-r0","apk:libcurl":"8.17.0-r1","apk:libexpat":"2.7.3-r0","apk:libgcc":"15.2.0-r2","apk:libgomp":"15.2.0-r2","apk:libidn2":"2.3.8-r0","apk:libpsl":"0.21.5-r3","apk:libssl3":"3.5.4-r0","apk:libstdc++":"15.2.0-r2","apk:libunistring":"1.4.1-r0","apk:mpc1":"1.3.1-r1","apk:mpfr4":"4.2.2-r0","apk:musl":"1.2.5-r21","apk:musl-dev":"1.2.5-r21","apk:nghttp2-libs":"1.68.0-r0","apk:nghttp3":"1.13.1-r0","apk:pcre2":"10.47-r0","apk:zlib":"1.3.1-r2","apk:zstd-libs":"1.5.7-r2","https://github.com/ergochat/ergo":"v2.17.0"}

FROM reg.g5d.dev/golang:latest AS build

RUN apk add --no-cache --virtual .clone-deps \
    brotli-libs=1.2.0-r0 \
    c-ares=1.34.6-r0 \
    ca-certificates-bundle=20251003-r0 \
    git=2.52.0-r0 \
    libcrypto3=3.5.4-r0 \
    libcurl=8.17.0-r1 \
    libexpat=2.7.3-r0 \
    libidn2=2.3.8-r0 \
    libpsl=0.21.5-r3 \
    libssl3=3.5.4-r0 \
    libunistring=1.4.1-r0 \
    musl=1.2.5-r21 \
    nghttp2-libs=1.68.0-r0 \
    nghttp3=1.13.1-r0 \
    pcre2=10.47-r0 \
    zlib=1.3.1-r2 \
    zstd-libs=1.5.7-r2 \
    ;

# Clone repository
RUN git clone --depth=1 --branch v2.17.0 "https://github.com/ergochat/ergo" /src/ergochat/ergo
RUN apk del --no-network .clone-deps

RUN apk add --no-cache --virtual .build-go-only-deps \
    binutils=2.45.1-r0 \
    gcc=15.2.0-r2 \
    gmp=6.3.0-r4 \
    go=1.25.5-r0 \
    isl25=0.25-r2 \
    jansson=2.14.1-r0 \
    libatomic=15.2.0-r2 \
    libgcc=15.2.0-r2 \
    libgomp=15.2.0-r2 \
    libstdc++=15.2.0-r2 \
    mpc1=1.3.1-r1 \
    mpfr4=4.2.2-r0 \
    musl=1.2.5-r21 \
    musl-dev=1.2.5-r21 \
    zlib=1.3.1-r2 \
    zstd-libs=1.5.7-r2 \
    ;

# Download dependencies
WORKDIR /src/ergochat/ergo
RUN go mod download
# Build binary
RUN CGO_ENABLED=0 go build -trimpath -tags 'netgo,osusergo' -ldflags='-s -w -extldflags "-static"' -o /ergo .
# Generate license notices
RUN go run github.com/google/go-licenses@latest save . --save_path=/notices/ergo
RUN apk del --no-network .build-go-only-deps

RUN apk add --no-cache --virtual .create-directories-deps \
    busybox=1.37.0-r30 \
    musl=1.2.5-r21 \
    ;

# Create directories
RUN mkdir -p /ircd /db; \
    chmod 777 /ircd; \
    chown 65532:65532 /ircd; \
    chmod 777 /db; \
    chown 65532:65532 /db
RUN apk del --no-network .create-directories-deps


FROM reg.g5d.dev/base:latest AS rootfs

COPY --from=build /ergo /rootfs/ergo

COPY --from=build /notices/ergo /rootfs/notices/ergo

COPY --from=build /ircd /rootfs/ircd

COPY --from=build /db /rootfs/db

COPY --from=build /src/ergochat/ergo/languages/ /rootfs/languages/


FROM reg.g5d.dev/base:latest

COPY --from=rootfs /rootfs/ /

EXPOSE 8080

ENTRYPOINT ["/ergo"]

CMD ["run", "--conf", "/ircd/ircd.yaml"]


