package:
  name: ergo
  description: ergo service

versions:
  "https://github.com/ergochat/ergo": latest

stages:
  - template: multi-go-app
    with:
      binaries:
        - repo: https://github.com/ergochat/ergo
          tag: "%{versions.https://github.com/ergochat/ergo}"
          binary: ergo
      extra-copies:
        - from: /src/ergochat/ergo/languages/
          to: /languages/
      expose:
        - "8080"
      volumes:
        - path: /ircd
        - path: /db
      entrypoint:
        - /ergo
      cmd:
        - run
        - --conf
        - /ircd/ircd.yaml
