FROM {{image "golang"}} AS build
{{template "clone" (map "repo" "greboid/registryauth")}}
{{template "build-go" (map "subdir" "./cmd/authedreg")}}
{{template "go-licenses" (map)}}
{{template "prepare" (map "name" "registryauth" "volumes" (arr "/data"))}}
{{template "runtime" (map "name" "registryauth" "exposes" (arr "8080") "volumes" (arr "/data"))}}
