package:
  name: registryauth
  description: registryauth service

stages:
  - name: build
    environment:
      base-image: golang
    pipeline:
      - name: Clone and build registryauth
        uses: clone-and-build-go
        with:
          repo: https://github.com/greboid/registryauth
          package: ./cmd/auth
  - name: rootfs
    environment:
      base-image: base
    pipeline:
      - name: Copy binary and notices to rootfs
        copy:
          from-stage: build
          from: /main
          to: /rootfs/registryauth
      - copy:
          from-stage: build
          from: /notices
          to: /rootfs/notices
  - name: Final
    environment:
      base-image: base
      expose:
        - "8080"
      entrypoint:
        - /registryauth
    pipeline:
      - name: Copy rootfs to root
        copy:
          from-stage: rootfs
          from: /rootfs/
          to: /
