FROM {{image "golang"}} AS build
{{template "clone" (map "url" "https://tangled.org/tangled.org/core" "tag" (git_tag "https://tangled.org/tangled.org/core" "unreleased"))}}
{{template "build-go" (map "cgo" "true" "subdir" "./cmd/spindle")}}
{{template "go-licenses" (map "ignores" (arr "github.com/ipfs/bbloom" "github.com/multiformats/go-base36" "gitlab.com/yawning/secp256k1-voi/internal/fiat/secp256k1montgomery"))}}
{{template "prepare" (map "name" "spindle")}}
{{template "runtime" (map "name" "spindle" "runtime_image" "baseroot")}}
