# BOM: {"apk:brotli-libs":"1.2.0-r0","apk:busybox-static":"1.37.0-r30","apk:c-ares":"1.34.6-r0","apk:ca-certificates-bundle":"20251003-r0","apk:git":"2.52.0-r0","apk:libcrypto3":"3.5.4-r0","apk:libcurl":"8.17.0-r1","apk:libexpat":"2.7.3-r0","apk:libgcc":"15.2.0-r2","apk:libidn2":"2.3.8-r0","apk:libpsl":"0.21.5-r3","apk:libssl3":"3.5.4-r0","apk:libstdc++":"15.2.0-r2","apk:libunistring":"1.4.1-r0","apk:musl":"1.2.5-r21","apk:nghttp2-libs":"1.68.0-r0","apk:nghttp3":"1.13.1-r0","apk:pcre2":"10.47-r0","apk:zlib":"1.3.1-r2","apk:zstd-libs":"1.5.7-r2","image:alpine":"94817fe036e2a98186058c6382acc6bfbe05dbfed4fbecfb617ef0a3691d9cee","image:base":"f51cf2b2d5f5b7673f814fd7e2c4ae0809cd02e4d78ec19bc732028345c366f8","image:node":"5b570659b3d09495893af78c34347e46ae437208e1001b13dc09129f745ddae9","image:sws":"fc62b047c39aa9bca726b97f86f8c8a60c6fa6ef9422c8d5a38f64d6a539cca4"}

FROM reg.g5d.dev/alpine@sha256:94817fe036e2a98186058c6382acc6bfbe05dbfed4fbecfb617ef0a3691d9cee AS busybox

# Install packages
RUN set -eux; \
    apk add --no-cache \
        busybox-static=1.37.0-r30 \
    ;


FROM reg.g5d.dev/node@sha256:5b570659b3d09495893af78c34347e46ae437208e1001b13dc09129f745ddae9 AS builder

WORKDIR /app

# Clone and build gamja
RUN apk add --no-cache --virtual .build-deps \
  brotli-libs=1.2.0-r0 \
  c-ares=1.34.6-r0 \
  ca-certificates-bundle=20251003-r0 \
  git=2.52.0-r0 \
  libcrypto3=3.5.4-r0 \
  libcurl=8.17.0-r1 \
  libexpat=2.7.3-r0 \
  libgcc=15.2.0-r2 \
  libidn2=2.3.8-r0 \
  libpsl=0.21.5-r3 \
  libssl3=3.5.4-r0 \
  libstdc++=15.2.0-r2 \
  libunistring=1.4.1-r0 \
  musl=1.2.5-r21 \
  nghttp2-libs=1.68.0-r0 \
  nghttp3=1.13.1-r0 \
  pcre2=10.47-r0 \
  zlib=1.3.1-r2 \
  zstd-libs=1.5.7-r2 \
  ; \
  set -eux; \
  git clone https://codeberg.org/emersion/gamja.git; \
  cd gamja; \
  npm install --include=dev; \
  npm run build; \
  apk del --no-network .build-deps


FROM reg.g5d.dev/base@sha256:f51cf2b2d5f5b7673f814fd7e2c4ae0809cd02e4d78ec19bc732028345c366f8 AS rootfs

# Copy gamja dist to rootfs
COPY --from=builder --chown=65532:65532 /app/gamja/dist /rootfs/public

# Copy busybox to rootfs
COPY --from=busybox /bin/busybox.static /rootfs/bin/sh

# Copy wrapper script to rootfs
# Copy gamja to /rootfs/usr/local/bin/gamja
COPY --chmod=755 gamja /rootfs/usr/local/bin/gamja


FROM reg.g5d.dev/sws@sha256:fc62b047c39aa9bca726b97f86f8c8a60c6fa6ef9422c8d5a38f64d6a539cca4

# Copy rootfs to root
COPY --from=rootfs --chown=65532:65532 /rootfs/ /

ENTRYPOINT ["gamja"]


