# BOM: {"apk:brotli-libs":"1.2.0-r0","apk:busybox-static":"1.37.0-r30","apk:c-ares":"1.34.6-r0","apk:ca-certificates-bundle":"20251003-r0","apk:git":"2.52.0-r0","apk:libcrypto3":"3.5.4-r0","apk:libcurl":"8.17.0-r1","apk:libexpat":"2.7.3-r0","apk:libgcc":"15.2.0-r2","apk:libidn2":"2.3.8-r0","apk:libpsl":"0.21.5-r3","apk:libssl3":"3.5.4-r0","apk:libstdc++":"15.2.0-r2","apk:libunistring":"1.4.1-r0","apk:musl":"1.2.5-r21","apk:nghttp2-libs":"1.68.0-r0","apk:nghttp3":"1.13.1-r0","apk:pcre2":"10.47-r0","apk:zlib":"1.3.1-r2","apk:zstd-libs":"1.5.7-r2","image:alpine":"8460e063222dd90995eb53b4162ee28277f69ce9035813bbfd1297c95444e806","image:base":"98bf705f4c9616325e99c0c2d98ba33b395876662c7874db4798b91b325d3dc1","image:node":"a85e7e8102b80224985b68c759f945465dcf06b87118cd71589fbe9bf7ee5dfa","image:sws":"3b9bf9a53326635cf1f9d3b2baa3583fb72ea1a0a716f885cb8f328bbe17ccfd"}

FROM reg.g5d.dev/alpine@sha256:8460e063222dd90995eb53b4162ee28277f69ce9035813bbfd1297c95444e806 AS busybox

# Install packages
RUN set -eux; \
    apk add --no-cache \
        busybox-static=1.37.0-r30 \
    ;


FROM reg.g5d.dev/node@sha256:a85e7e8102b80224985b68c759f945465dcf06b87118cd71589fbe9bf7ee5dfa AS builder

WORKDIR /app

# Clone and build gamja
RUN apk add --no-cache --virtual .build-deps \
  brotli-libs=1.2.0-r0 \
  c-ares=1.34.6-r0 \
  ca-certificates-bundle=20251003-r0 \
  git=2.52.0-r0 \
  libcrypto3=3.5.4-r0 \
  libcurl=8.17.0-r1 \
  libexpat=2.7.3-r0 \
  libgcc=15.2.0-r2 \
  libidn2=2.3.8-r0 \
  libpsl=0.21.5-r3 \
  libssl3=3.5.4-r0 \
  libstdc++=15.2.0-r2 \
  libunistring=1.4.1-r0 \
  musl=1.2.5-r21 \
  nghttp2-libs=1.68.0-r0 \
  nghttp3=1.13.1-r0 \
  pcre2=10.47-r0 \
  zlib=1.3.1-r2 \
  zstd-libs=1.5.7-r2 \
  ; \
  set -eux; \
  git clone https://codeberg.org/emersion/gamja.git; \
  cd gamja; \
  npm install --include=dev; \
  npm run build; \
  apk del --no-network .build-deps


FROM reg.g5d.dev/base@sha256:98bf705f4c9616325e99c0c2d98ba33b395876662c7874db4798b91b325d3dc1 AS rootfs

# Copy gamja dist to rootfs
COPY --from=builder --chown=65532:65532 /app/gamja/dist /rootfs/public

# Copy busybox to rootfs
COPY --from=busybox /bin/busybox.static /rootfs/bin/sh

# Copy wrapper script to rootfs
# Copy gamja to /rootfs/usr/local/bin/gamja
COPY --chmod=755 gamja /rootfs/usr/local/bin/gamja


FROM reg.g5d.dev/sws@sha256:3b9bf9a53326635cf1f9d3b2baa3583fb72ea1a0a716f885cb8f328bbe17ccfd

# Copy rootfs to root
COPY --from=rootfs --chown=65532:65532 /rootfs/ /

ENTRYPOINT ["gamja"]


