# BOM: {"apk:brotli-libs":"1.2.0-r0","apk:busybox-static":"1.37.0-r30","apk:c-ares":"1.34.6-r0","apk:ca-certificates-bundle":"20251003-r0","apk:git":"2.52.0-r0","apk:libcrypto3":"3.5.4-r0","apk:libcurl":"8.17.0-r1","apk:libexpat":"2.7.3-r0","apk:libgcc":"15.2.0-r2","apk:libidn2":"2.3.8-r0","apk:libpsl":"0.21.5-r3","apk:libssl3":"3.5.4-r0","apk:libstdc++":"15.2.0-r2","apk:libunistring":"1.4.1-r0","apk:musl":"1.2.5-r21","apk:nghttp2-libs":"1.68.0-r0","apk:nghttp3":"1.13.1-r0","apk:pcre2":"10.47-r0","apk:zlib":"1.3.1-r2","apk:zstd-libs":"1.5.7-r2","image:alpine":"977a0b2b64bef64b8b459d572f34b491f8ca974ed1314be93aa1f08bb5f9eb66","image:base":"33f63440d98cb05f5b1b1cb1c870640d4c6b54067f11b30d65861bd120823b03","image:node":"b8d1a00e49204d97a565fbf7a5c6ee4da0edd7db164c7626343353e21bcce1d4","image:sws":"9d4a9a79aef9b55f3df6dcf47461799b15731caa2ac409f614ae0c222372a13b"}

FROM reg.g5d.dev/alpine@sha256:977a0b2b64bef64b8b459d572f34b491f8ca974ed1314be93aa1f08bb5f9eb66 AS busybox

# Install packages
RUN set -eux; \
    apk add --no-cache \
        busybox-static=1.37.0-r30 \
    ;


FROM reg.g5d.dev/node@sha256:b8d1a00e49204d97a565fbf7a5c6ee4da0edd7db164c7626343353e21bcce1d4 AS builder

WORKDIR /app

# Clone and build gamja
RUN apk add --no-cache --virtual .build-deps \
  brotli-libs=1.2.0-r0 \
  c-ares=1.34.6-r0 \
  ca-certificates-bundle=20251003-r0 \
  git=2.52.0-r0 \
  libcrypto3=3.5.4-r0 \
  libcurl=8.17.0-r1 \
  libexpat=2.7.3-r0 \
  libgcc=15.2.0-r2 \
  libidn2=2.3.8-r0 \
  libpsl=0.21.5-r3 \
  libssl3=3.5.4-r0 \
  libstdc++=15.2.0-r2 \
  libunistring=1.4.1-r0 \
  musl=1.2.5-r21 \
  nghttp2-libs=1.68.0-r0 \
  nghttp3=1.13.1-r0 \
  pcre2=10.47-r0 \
  zlib=1.3.1-r2 \
  zstd-libs=1.5.7-r2 \
  ; \
  set -eux; \
  git clone https://codeberg.org/emersion/gamja.git; \
  cd gamja; \
  npm install --include=dev; \
  npm run build; \
  apk del --no-network .build-deps


FROM reg.g5d.dev/base@sha256:33f63440d98cb05f5b1b1cb1c870640d4c6b54067f11b30d65861bd120823b03 AS rootfs

# Copy gamja dist to rootfs
COPY --from=builder --chown=65532:65532 /app/gamja/dist /rootfs/public

# Copy busybox to rootfs
COPY --from=busybox /bin/busybox.static /rootfs/bin/sh

# Copy wrapper script to rootfs
# Copy gamja to /rootfs/usr/local/bin/gamja
COPY --chmod=755 gamja /rootfs/usr/local/bin/gamja


FROM reg.g5d.dev/sws@sha256:9d4a9a79aef9b55f3df6dcf47461799b15731caa2ac409f614ae0c222372a13b

# Copy rootfs to root
COPY --from=rootfs --chown=65532:65532 /rootfs/ /

ENTRYPOINT ["gamja"]


