package:
  name: gamja
  description: Simple IRC web client

stages:
  - name: busybox
    environment:
      base-image: alpine
      packages:
        - busybox-static
    pipeline: []

  - name: builder
    environment:
      base-image: node
      workdir: /app
    pipeline:
      - name: Clone and build gamja
        build-deps:
          - git
        run: |
          set -eux;
          git clone https://codeberg.org/emersion/gamja.git
          cd gamja
          npm install --include=dev
          npm run build

  - name: rootfs
    environment:
      base-image: base
    pipeline:
      - name: Copy gamja dist to rootfs
        copy:
          from-stage: builder
          from: /app/gamja/dist
          to: /rootfs/public
          chown: "65532:65532"
      - name: Copy busybox to rootfs
        copy:
          from-stage: busybox
          from: /bin/busybox.static
          to: /rootfs/bin/sh
      - name: Copy wrapper script to rootfs
        uses: copy-files
        with:
          files:
            - from: gamja
              to: /rootfs/usr/local/bin/gamja
              chmod: "755"

  - name: Final
    environment:
      base-image: sws
      entrypoint:
        - gamja
    pipeline:
      - name: Copy rootfs to root
        copy:
          from-stage: rootfs
          from: /rootfs/
          to: /
          chown: "65532:65532"
