package:
  name: puzzles
  version: 1.0.2
  epoch: 0
  target-architecture:
    - x86_64
update:
  enabled: true
  git:
    strip-prefix: v
environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/v3.22/main
    packages:
      - go
      - busybox
      - ca-certificates-bundle
  environment:
    GOPROXY: "https://proxy.golang.org"
pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/greboid/puzzles
      tag: v${{package.version}}
  - uses: go/build
    with:
      packages: .
      output: puzzles
      strip: -w -s
      ldflags: -extldflags "-static" -buildid=
  - runs: |
      # Copy wordlists
      mkdir -p "${{targets.destdir}}"/app/wordlists
      cp -r wordlists/. "${{targets.destdir}}"/app/wordlists/
test:
  pipeline:
    - runs: puzzles --help
