package:
  name: rust
  version: 1.90.0
  epoch: 0
  description: Rust programming language toolchain
  target-architecture:
    - x86_64
update:
  enabled: true
  git:
    strip-prefix: v
environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/v3.22/main
    packages:
      - busybox
      - ca-certificates-bundle
      - bash
      - libgcc
      - musl-utils
      - curl
  environment:
    RUSTUP_HOME: "/usr/local/rustup"
    CARGO_HOME: "/usr/local/cargo"
    RUST_VERSION: "1.90.0"
    RUSTUP_VERSION: "1.28.2"
pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/rust-lang/rust.git
  - runs: |
      # Download rustup-init
      curl -sfLo /tmp/rustup-init https://static.rust-lang.org/rustup/archive/${RUSTUP_VERSION}/x86_64-unknown-linux-musl/rustup-init
      curl -sfLo /tmp/rustup-init.sha256 https://static.rust-lang.org/rustup/archive/${RUSTUP_VERSION}/x86_64-unknown-linux-musl/rustup-init.sha256

      # Verify checksum
      cd /tmp
      echo "$(cat rustup-init.sha256 | awk '{print $1}') *rustup-init" | sha256sum -wc -

      # Install rust
      chmod +x rustup-init
      ./rustup-init -y --no-modify-path --profile minimal --default-toolchain ${RUST_VERSION} --default-host x86_64-unknown-linux-musl

      # Copy to destdir
      mkdir -p "${{targets.destdir}}"/usr/local/rustup
      mkdir -p "${{targets.destdir}}"/usr/local/cargo
      mkdir -p "${{targets.destdir}}"/usr/local/bin

      cp -a /usr/local/rustup/* "${{targets.destdir}}"/usr/local/rustup/
      cp -a /usr/local/cargo/* "${{targets.destdir}}"/usr/local/cargo/

      # Create symlink
      ln -s /usr/local/cargo/bin/cargo "${{targets.destdir}}"/usr/local/bin/cargo
test:
  pipeline:
    - runs: cargo --version
