package:
  name: soju
  version: 0.9.0
  epoch: 0
  description: IRC bouncer with SQLite support
  target-architecture:
    - x86_64
update:
  enabled: true
  git:
    strip-prefix: v
environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/v3.22/main
    packages:
      - go
      - busybox
      - ca-certificates-bundle
  environment:
    GOPROXY: "https://proxy.golang.org"
pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/emersion/soju
      tag: v${{package.version}}
  - uses: go/build
    with:
      packages: ./cmd/soju
      output: soju
      strip: -w -s
      ldflags: -extldflags "-static" -buildid=
      tags: moderncsqlite
  - uses: go/build
    with:
      packages: ./cmd/sojuctl
      output: sojuctl
      strip: -w -s
      ldflags: -extldflags "-static" -buildid=
      tags: moderncsqlite
  - uses: go/build
    with:
      packages: ./cmd/sojudb
      output: sojudb
      strip: -w -s
      ldflags: -extldflags "-static" -buildid=
      tags: moderncsqlite
test:
  pipeline:
    - runs: soju --help
