package:
  name: centauri
  description: centauri service

stages:
  - template: go-app
    with:
      repo: https://github.com/csmith/centauri
      binary: centauri
      package: ./cmd/centauri
      expose:
        - "8080"