package:
  name: centauri
  description: centauri service

stages:
  - name: build
    environment:
      base-image: golang
    pipeline:
      - name: Clone and Build Centauri
        uses: clone-and-build-go
        with:
          repo: https://github.com/csmith/centauri
          package: ./cmd/centauri
  - name: rootfs
    environment:
      base-image: base
    pipeline:
      - name: Copy binary and notices to rootfs
        copy:
          from-stage: build
          from: /main
          to: /rootfs/centauri
      - name: Copy license notices to rootfs
        copy:
          from-stage: build
          from: /notices
          to: /rootfs/notices
  - name: final
    environment:
      base-image: base
      expose:
        - "8080"
      entrypoint:
        - /centauri
    pipeline:
      - name: Copy rootfs to root
        copy:
          from-stage: rootfs
          from: /rootfs/
          to: /
