package:
  name: centauri
  description: centauri service

versions:
  "https://github.com/csmith/centauri.git": latest

stages:
  - template: go-app
    with:
      repo: https://github.com/csmith/centauri
      tag: "%{versions.https://github.com/csmith/centauri.git}"
      ignore:
        - github.com/go-acme/tencentclouddnspod/v20210323
        - github.com/go-acme/tencentedgdeone/v20220901
        - github.com/nrdcg/oci-go-sdk/common/v1065
        - github.com/nrdcg/oci-go-sdk/common/v1065/auth
        - github.com/nrdcg/oci-go-sdk/common/v1065/utils
        - github.com/nrdcg/oci-go-sdk/dns/v1065
      go-tags: lego_httpreq
      binary: centauri
      package: ./cmd/centauri
      expose:
        - "8080"
