package:
  name: centauri
  description: centauri service

versions:
  "https://github.com/csmith/centauri.git": latest

stages:
  - template: go-app
    with:
      repo: https://github.com/csmith/centauri
      tag: "%{versions.https://github.com/csmith/centauri.git}"
      binary: centauri
      package: ./cmd/centauri
      expose:
        - "8080"
