name: build
on:
  push:
    branches: [master]
  workflow_dispatch:

enable-openid-connect: true

jobs:
  build:
    uses: containers/build-common/.forgejo/workflows/build.yml@master
    with:
      image: pocket-id
      alpine: "3.24"
      mirror: false
    secrets: inherit
