
on:
  workflow_dispatch:
  schedule:
    - cron: '42 12 * * *'
  push:
    paths-ignore:
      - '**/Containerfile'
      - '**/Dockerfile'
      - '.github/**'
      - 'README.md'
name: Update Containers
concurrency: dockerfiles
permissions:
  contents: write
jobs:
  setup-cache:
    name: Setup cache
    runs-on: ubuntu-latest
    steps:
        - name: Cache contempt
          uses: actions/cache@v6
          id: cache
          with:
              path: ~/go/bin/contempt
              key: contempt-${{ runner.os }}-${{ runner.arch }}-latest
        - name: Install latest contempt
          if: steps.cache.outputs.cache-hit != 'true'
          run: go install github.com/csmith/contempt/cmd/contempt@latest
  
  alpine:
    name: Build alpine
    needs:
        - setup-cache

    uses: ./.github/workflows/container-builder.yml
    secrets: inherit
    with:
        PROJECT_NAME: alpine

  baseroot:
    name: Build baseroot
    needs:
        - setup-cache
        - alpine
    uses: ./.github/workflows/container-builder.yml
    secrets: inherit
    with:
        PROJECT_NAME: baseroot

  git:
    name: Build git
    needs:
        - setup-cache
        - alpine
    uses: ./.github/workflows/container-builder.yml
    secrets: inherit
    with:
        PROJECT_NAME: git

  golang:
    name: Build golang
    needs:
        - setup-cache
        - alpine
    uses: ./.github/workflows/container-builder.yml
    secrets: inherit
    with:
        PROJECT_NAME: golang

  rust:
    name: Build rust
    needs:
        - setup-cache
        - alpine
    uses: ./.github/workflows/container-builder.yml
    secrets: inherit
    with:
        PROJECT_NAME: rust

  base:
    name: Build base
    needs:
        - setup-cache
        - baseroot
    uses: ./.github/workflows/container-builder.yml
    secrets: inherit
    with:
        PROJECT_NAME: base

  dind:
    name: Build dind
    needs:
        - setup-cache
        - alpine
        - baseroot
    uses: ./.github/workflows/container-builder.yml
    secrets: inherit
    with:
        PROJECT_NAME: dind

  centauri:
    name: Build centauri
    needs:
        - setup-cache
        - alpine
        - base
        - golang
    uses: ./.github/workflows/container-builder.yml
    secrets: inherit
    with:
        PROJECT_NAME: centauri

  centauri-docker-confd:
    name: Build centauri-docker-confd
    needs:
        - setup-cache
        - alpine
        - base
        - golang
    uses: ./.github/workflows/container-builder.yml
    secrets: inherit
    with:
        PROJECT_NAME: centauri-docker-confd

  cocoon:
    name: Build cocoon
    needs:
        - setup-cache
        - alpine
        - base
        - golang
    uses: ./.github/workflows/container-builder.yml
    secrets: inherit
    with:
        PROJECT_NAME: cocoon

  dockercleanup:
    name: Build dockercleanup
    needs:
        - setup-cache
        - alpine
        - base
        - golang
    uses: ./.github/workflows/container-builder.yml
    secrets: inherit
    with:
        PROJECT_NAME: dockercleanup

  dsp:
    name: Build dsp
    needs:
        - setup-cache
        - alpine
        - base
        - golang
    uses: ./.github/workflows/container-builder.yml
    secrets: inherit
    with:
        PROJECT_NAME: dsp

  ergo:
    name: Build ergo
    needs:
        - setup-cache
        - alpine
        - base
        - golang
    uses: ./.github/workflows/container-builder.yml
    secrets: inherit
    with:
        PROJECT_NAME: ergo

  forgejo:
    name: Build forgejo
    needs:
        - setup-cache
        - alpine
        - base
        - git
        - golang
    uses: ./.github/workflows/container-builder.yml
    secrets: inherit
    with:
        PROJECT_NAME: forgejo

  forgejo-runner:
    name: Build forgejo-runner
    needs:
        - setup-cache
        - alpine
        - base
        - git
        - golang
    uses: ./.github/workflows/container-builder.yml
    secrets: inherit
    with:
        PROJECT_NAME: forgejo-runner

  githubmirror:
    name: Build githubmirror
    needs:
        - setup-cache
        - alpine
        - base
        - golang
    uses: ./.github/workflows/container-builder.yml
    secrets: inherit
    with:
        PROJECT_NAME: githubmirror

  golink:
    name: Build golink
    needs:
        - setup-cache
        - alpine
        - base
        - golang
    uses: ./.github/workflows/container-builder.yml
    secrets: inherit
    with:
        PROJECT_NAME: golink

  goplum:
    name: Build goplum
    needs:
        - setup-cache
        - alpine
        - base
        - golang
    uses: ./.github/workflows/container-builder.yml
    secrets: inherit
    with:
        PROJECT_NAME: goplum

  httpredirect:
    name: Build httpredirect
    needs:
        - setup-cache
        - alpine
        - base
        - golang
    uses: ./.github/workflows/container-builder.yml
    secrets: inherit
    with:
        PROJECT_NAME: httpredirect

  identd:
    name: Build identd
    needs:
        - setup-cache
        - alpine
        - base
        - golang
    uses: ./.github/workflows/container-builder.yml
    secrets: inherit
    with:
        PROJECT_NAME: identd

  irc-bot:
    name: Build irc-bot
    needs:
        - setup-cache
        - alpine
        - base
        - golang
    uses: ./.github/workflows/container-builder.yml
    secrets: inherit
    with:
        PROJECT_NAME: irc-bot

  irc-distribution:
    name: Build irc-distribution
    needs:
        - setup-cache
        - alpine
        - base
        - golang
    uses: ./.github/workflows/container-builder.yml
    secrets: inherit
    with:
        PROJECT_NAME: irc-distribution

  irc-github:
    name: Build irc-github
    needs:
        - setup-cache
        - alpine
        - base
        - golang
    uses: ./.github/workflows/container-builder.yml
    secrets: inherit
    with:
        PROJECT_NAME: irc-github

  irc-goplum:
    name: Build irc-goplum
    needs:
        - setup-cache
        - alpine
        - base
        - golang
    uses: ./.github/workflows/container-builder.yml
    secrets: inherit
    with:
        PROJECT_NAME: irc-goplum

  irc-notifier:
    name: Build irc-notifier
    needs:
        - setup-cache
        - alpine
        - base
        - golang
    uses: ./.github/workflows/container-builder.yml
    secrets: inherit
    with:
        PROJECT_NAME: irc-notifier

  irc-webhook:
    name: Build irc-webhook
    needs:
        - setup-cache
        - alpine
        - base
        - golang
    uses: ./.github/workflows/container-builder.yml
    secrets: inherit
    with:
        PROJECT_NAME: irc-webhook

  knot:
    name: Build knot
    needs:
        - setup-cache
        - alpine
        - base
        - git
        - golang
    uses: ./.github/workflows/container-builder.yml
    secrets: inherit
    with:
        PROJECT_NAME: knot

  knotssh:
    name: Build knotssh
    needs:
        - setup-cache
        - alpine
        - base
        - git
        - golang
    uses: ./.github/workflows/container-builder.yml
    secrets: inherit
    with:
        PROJECT_NAME: knotssh

  linx-server:
    name: Build linx-server
    needs:
        - setup-cache
        - alpine
        - base
        - golang
    uses: ./.github/workflows/container-builder.yml
    secrets: inherit
    with:
        PROJECT_NAME: linx-server

  miniflux:
    name: Build miniflux
    needs:
        - setup-cache
        - alpine
        - base
        - golang
    uses: ./.github/workflows/container-builder.yml
    secrets: inherit
    with:
        PROJECT_NAME: miniflux

  pdsps:
    name: Build pdsps
    needs:
        - setup-cache
        - alpine
        - base
        - golang
    uses: ./.github/workflows/container-builder.yml
    secrets: inherit
    with:
        PROJECT_NAME: pdsps

  postgres-18:
    name: Build postgres-18
    needs:
        - setup-cache
        - alpine
        - base
    uses: ./.github/workflows/container-builder.yml
    secrets: inherit
    with:
        PROJECT_NAME: postgres-18

  purser:
    name: Build purser
    needs:
        - setup-cache
        - alpine
        - base
        - golang
    uses: ./.github/workflows/container-builder.yml
    secrets: inherit
    with:
        PROJECT_NAME: purser

  puzzles:
    name: Build puzzles
    needs:
        - setup-cache
        - alpine
        - base
        - golang
    uses: ./.github/workflows/container-builder.yml
    secrets: inherit
    with:
        PROJECT_NAME: puzzles

  redis:
    name: Build redis
    needs:
        - setup-cache
        - alpine
        - base
    uses: ./.github/workflows/container-builder.yml
    secrets: inherit
    with:
        PROJECT_NAME: redis

  registryauth:
    name: Build registryauth
    needs:
        - setup-cache
        - alpine
        - base
        - golang
    uses: ./.github/workflows/container-builder.yml
    secrets: inherit
    with:
        PROJECT_NAME: registryauth

  soju:
    name: Build soju
    needs:
        - setup-cache
        - alpine
        - base
        - golang
    uses: ./.github/workflows/container-builder.yml
    secrets: inherit
    with:
        PROJECT_NAME: soju

  spindle:
    name: Build spindle
    needs:
        - setup-cache
        - alpine
        - base
        - golang
    uses: ./.github/workflows/container-builder.yml
    secrets: inherit
    with:
        PROJECT_NAME: spindle

  sws:
    name: Build sws
    needs:
        - setup-cache
        - alpine
        - base
        - rust
    uses: ./.github/workflows/container-builder.yml
    secrets: inherit
    with:
        PROJECT_NAME: sws

  tailscale:
    name: Build tailscale
    needs:
        - setup-cache
        - alpine
        - base
        - golang
    uses: ./.github/workflows/container-builder.yml
    secrets: inherit
    with:
        PROJECT_NAME: tailscale

  thp:
    name: Build thp
    needs:
        - setup-cache
        - alpine
        - base
        - golang
    uses: ./.github/workflows/container-builder.yml
    secrets: inherit
    with:
        PROJECT_NAME: thp

  tsp:
    name: Build tsp
    needs:
        - setup-cache
        - alpine
        - base
        - golang
    uses: ./.github/workflows/container-builder.yml
    secrets: inherit
    with:
        PROJECT_NAME: tsp

  webhooked:
    name: Build webhooked
    needs:
        - setup-cache
        - alpine
        - base
        - golang
    uses: ./.github/workflows/container-builder.yml
    secrets: inherit
    with:
        PROJECT_NAME: webhooked

