FROM {{image "golang"}} AS build
{{template "clone" (map "repo" "csmith/tsp")}}
{{template "build-go" (map)}}
{{template "prepare" (map "name" "tsp" "skip_notices" true "volumes" (arr "/home/nonroot/.config" "/config"))}}
{{template "runtime" (map "name" "tsp" "exposes" (arr "8080" "8443") "volumes" (arr "/home/nonroot/.config" "/config"))}}
