package:
  name: tsp
  description: tsp service

stages:
  - name: build
    environment:
      base-image: golang
      packages:
        - git
    pipeline:
      - name: Clone and build
        uses: clone-and-build-go
        with:
          repo: https://github.com/csmith/tsp

  - name: rootfs
    environment:
      base-image: base
    pipeline:
      - name: Copy binary and notices to rootfs
        copy:
          from-stage: build
          from: /main
          to: /rootfs/tsp

      - copy:
          from-stage: build
          from: /notices
          to: /rootfs/notices

  - name: Final
    environment:
      base-image: base
      expose:
        - "8080"
      entrypoint:
        - /tsp

    pipeline:
      - name: Copy rootfs to root
        copy:
          from-stage: rootfs
          from: /rootfs/
          to: /
